name: ICONS Actions
run-name: ${{ github.actor }} revisando archivos 📂

on: [push]

jobs:
  explorar-codigo:
    runs-on: ubuntu-latest
    steps:
      # Paso 1: Descargar el código del repositorio al servidor
      - name: Checkout del código
        uses: actions/checkout@v4

      # Paso 2: Listar los archivos para verificar que están ahí
      - name: Ver archivos descargados
        run: ls -R